//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30128.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrcDotNet.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IrcDotNet.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set user mode for &apos;{0}&apos;..
        /// </summary>
        internal static string ErrorMessageCannotSetUserMode {
            get {
                return ResourceManager.GetString("ErrorMessageCannotSetUserMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The channel type &apos;{0}&apos; sent by the server is invalid..
        /// </summary>
        internal static string ErrorMessageInvalidChannelType {
            get {
                return ResourceManager.GetString("ErrorMessageInvalidChannelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message command name &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string ErrorMessageInvalidCommand {
            get {
                return ResourceManager.GetString("ErrorMessageInvalidCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command &apos;{0}&apos; was not recognised..
        /// </summary>
        internal static string ErrorMessageInvalidMessageCommand {
            get {
                return ResourceManager.GetString("ErrorMessageInvalidMessageCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The non-trailing parameter &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string ErrorMessageInvalidMiddleParameter {
            get {
                return ResourceManager.GetString("ErrorMessageInvalidMiddleParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified nick name is invalid..
        /// </summary>
        internal static string ErrorMessageInvalidNickName {
            get {
                return ResourceManager.GetString("ErrorMessageInvalidNickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified password is invalid..
        /// </summary>
        internal static string ErrorMessageInvalidPassword {
            get {
                return ResourceManager.GetString("ErrorMessageInvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message prefix &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string ErrorMessageInvalidPrefix {
            get {
                return ResourceManager.GetString("ErrorMessageInvalidPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified real name is invalid..
        /// </summary>
        internal static string ErrorMessageInvalidRealName {
            get {
                return ResourceManager.GetString("ErrorMessageInvalidRealName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source &apos;{0}&apos; of the message was not recognised as either a server or user..
        /// </summary>
        internal static string ErrorMessageInvalidSource {
            get {
                return ResourceManager.GetString("ErrorMessageInvalidSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A target name may not contain any &apos;,&apos; character..
        /// </summary>
        internal static string ErrorMessageInvalidTargetName {
            get {
                return ResourceManager.GetString("ErrorMessageInvalidTargetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The trailing parameter &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string ErrorMessageInvalidTrailingParameter {
            get {
                return ResourceManager.GetString("ErrorMessageInvalidTrailingParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified user mode is invalid..
        /// </summary>
        internal static string ErrorMessageInvalidUserMode {
            get {
                return ResourceManager.GetString("ErrorMessageInvalidUserMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified user name is invalid..
        /// </summary>
        internal static string ErrorMessageInvalidUserName {
            get {
                return ResourceManager.GetString("ErrorMessageInvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ISUPPORT message sent by the server contains an invalid PREFIX parameter..
        /// </summary>
        internal static string ErrorMessageISupportPrefixInvalid {
            get {
                return ResourceManager.GetString("ErrorMessageISupportPrefixInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of the line must not exceed 510 characters..
        /// </summary>
        internal static string ErrorMessageLineTooLong {
            get {
                return ResourceManager.GetString("ErrorMessageLineTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough mode parameters were specified for the given modes..
        /// </summary>
        internal static string ErrorMessageNotEnoughModeParameters {
            get {
                return ResourceManager.GetString("ErrorMessageNotEnoughModeParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message source &apos;{0}&apos; is not a user..
        /// </summary>
        internal static string ErrorMessageSourceNotUser {
            get {
                return ResourceManager.GetString("ErrorMessageSourceNotUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of the given target mask &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string ErrorMessageTargetMaskInvalidType {
            get {
                return ResourceManager.GetString("ErrorMessageTargetMaskInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target mask must be contain at least two characters..
        /// </summary>
        internal static string ErrorMessageTargetMaskTooShort {
            get {
                return ResourceManager.GetString("ErrorMessageTargetMaskTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more than 3 mode parameters may be sent per message..
        /// </summary>
        internal static string ErrorMessageTooManyModeParameters {
            get {
                return ResourceManager.GetString("ErrorMessageTooManyModeParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more than 15 command parameters may be specified..
        /// </summary>
        internal static string ErrorMessageTooManyParams {
            get {
                return ResourceManager.GetString("ErrorMessageTooManyParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value cannot be an empty string.
        /// </summary>
        internal static string ErrorMessageValueCannotBeEmptyString {
            get {
                return ResourceManager.GetString("ErrorMessageValueCannotBeEmptyString", resourceCulture);
            }
        }
    }
}
