//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrcDotNet.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IrcDotNet.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set user mode for &apos;{0}&apos;..
        /// </summary>
        internal static string MessageCannotSetUserMode {
            get {
                return ResourceManager.GetString("MessageCannotSetUserMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The channel type &apos;{0}&apos; sent by the server is invalid..
        /// </summary>
        internal static string MessageInvalidChannelType {
            get {
                return ResourceManager.GetString("MessageInvalidChannelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message command &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string MessageInvalidCommand {
            get {
                return ResourceManager.GetString("MessageInvalidCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command definition &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string MessageInvalidCommandDefinition {
            get {
                return ResourceManager.GetString("MessageInvalidCommandDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command &apos;{0}&apos; was not recognised..
        /// </summary>
        internal static string MessageInvalidMessageCommand {
            get {
                return ResourceManager.GetString("MessageInvalidMessageCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The non-trailing parameter &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string MessageInvalidMiddleParameter {
            get {
                return ResourceManager.GetString("MessageInvalidMiddleParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified nick name is invalid..
        /// </summary>
        internal static string MessageInvalidNickName {
            get {
                return ResourceManager.GetString("MessageInvalidNickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified password is invalid..
        /// </summary>
        internal static string MessageInvalidPassword {
            get {
                return ResourceManager.GetString("MessageInvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message prefix &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string MessageInvalidPrefix {
            get {
                return ResourceManager.GetString("MessageInvalidPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quoted character &apos;{0}&apos; was not recognised..
        /// </summary>
        internal static string MessageInvalidQuotedChar {
            get {
                return ResourceManager.GetString("MessageInvalidQuotedChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified real name is invalid..
        /// </summary>
        internal static string MessageInvalidRealName {
            get {
                return ResourceManager.GetString("MessageInvalidRealName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object provided for registration info is of an unknown type..
        /// </summary>
        internal static string MessageInvalidRegistrationInfoObject {
            get {
                return ResourceManager.GetString("MessageInvalidRegistrationInfoObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The registration info for a service must have a valid nick name and description..
        /// </summary>
        internal static string MessageInvalidServiceRegistrationInfo {
            get {
                return ResourceManager.GetString("MessageInvalidServiceRegistrationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source &apos;{0}&apos; of the message was not recognised as either a server or user..
        /// </summary>
        internal static string MessageInvalidSource {
            get {
                return ResourceManager.GetString("MessageInvalidSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message tag &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string MessageInvalidTag {
            get {
                return ResourceManager.GetString("MessageInvalidTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A target name may not contain any &apos;,&apos; character..
        /// </summary>
        internal static string MessageInvalidTargetName {
            get {
                return ResourceManager.GetString("MessageInvalidTargetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The trailing parameter &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string MessageInvalidTrailingParameter {
            get {
                return ResourceManager.GetString("MessageInvalidTrailingParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL scheme &apos;{0}&apos; is not valid..
        /// </summary>
        internal static string MessageInvalidUrlScheme {
            get {
                return ResourceManager.GetString("MessageInvalidUrlScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified user mode is invalid..
        /// </summary>
        internal static string MessageInvalidUserMode {
            get {
                return ResourceManager.GetString("MessageInvalidUserMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified user name is invalid..
        /// </summary>
        internal static string MessageInvalidUserName {
            get {
                return ResourceManager.GetString("MessageInvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The registration info for a user must have a valid nick name and user name..
        /// </summary>
        internal static string MessageInvalidUserRegistrationInfo {
            get {
                return ResourceManager.GetString("MessageInvalidUserRegistrationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ISUPPORT message sent by the server contains an invalid PREFIX parameter..
        /// </summary>
        internal static string MessageISupportPrefixInvalid {
            get {
                return ResourceManager.GetString("MessageISupportPrefixInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough mode parameters were specified for the given modes..
        /// </summary>
        internal static string MessageNotEnoughModeParameters {
            get {
                return ResourceManager.GetString("MessageNotEnoughModeParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The host name &apos;{0}&apos; does not resolve to a valid IP address..
        /// </summary>
        internal static string MessageNoValidAddress {
            get {
                return ResourceManager.GetString("MessageNoValidAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of a raw message must not exceed {0} characters..
        /// </summary>
        internal static string MessageRawMessageTooLong {
            get {
                return ResourceManager.GetString("MessageRawMessageTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message source &apos;{0}&apos; is not a user..
        /// </summary>
        internal static string MessageSourceNotUser {
            get {
                return ResourceManager.GetString("MessageSourceNotUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of the given target mask &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string MessageTargetMaskInvalidType {
            get {
                return ResourceManager.GetString("MessageTargetMaskInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target mask must be contain at least two characters..
        /// </summary>
        internal static string MessageTargetMaskTooShort {
            get {
                return ResourceManager.GetString("MessageTargetMaskTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more than 3 mode parameters may be sent per message..
        /// </summary>
        internal static string MessageTooManyModeParameters {
            get {
                return ResourceManager.GetString("MessageTooManyModeParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more than 15 command parameters may be specified..
        /// </summary>
        internal static string MessageTooManyParams {
            get {
                return ResourceManager.GetString("MessageTooManyParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value cannot be an empty string.
        /// </summary>
        internal static string MessageValueCannotBeEmptyString {
            get {
                return ResourceManager.GetString("MessageValueCannotBeEmptyString", resourceCulture);
            }
        }
    }
}
