// <auto-generated/>
using System.Reflection;

[assembly: AssemblyCompanyAttribute("IRC.NET")]
[assembly: AssemblyProductAttribute("IRC.NET")]
[assembly: AssemblyCopyrightAttribute("IRC.NET is copyright © Alex Regueiro 2011-2015")]
[assembly: AssemblyVersionAttribute("0.5.0")]
[assembly: AssemblyFileVersionAttribute("0.5.0")]
[assembly: AssemblyInformationalVersionAttribute("0.5.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.5.0";
    }
}
