// <auto-generated/>
using System.Reflection;

[assembly: AssemblyCompanyAttribute("IRC.Net")]
[assembly: AssemblyProductAttribute("IRC.Net")]
[assembly: AssemblyCopyrightAttribute("IRC.Net Copyright © Alex Regueiro 2011-2015 @")]
[assembly: AssemblyVersionAttribute("0.4.1.0")]
[assembly: AssemblyFileVersionAttribute("0.4.1.0")]
[assembly: AssemblyInformationalVersionAttribute("0.4.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.4.1.0";
    }
}
